services:
  postgres:
    image: postgres:17-alpine
    container_name: weather_postgres # <-- Добавил префикс, чтобы не конфликтовать со старым ботом
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./.postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432" # Наружный порт берем из .env (например 5433)
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
        compress: "true"
    networks:
      - weather_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: weather_pgadmin
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./.pgadmin_data:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT}:80"
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
        compress: "true"
    networks:
      - weather_network

  redis:
    image: redis:7.4-alpine
    container_name: weather_redis
    env_file:
      - .env
    volumes:
      - ./.redis_data:/data
    restart: unless-stopped
    ports:
      - "${REDIS_PORT}:6379"
    command: [ "redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}" ]
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "PING" ]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
        compress: "true"
    networks:
      - weather_network

  bot:
    build: .
    container_name: weather_bot # Переименовали под новый проект
    restart: always
    env_file:
      - .env
    environment:
      - DB_HOST=postgres # Оставляем имя сервиса (Docker сам найдет)
      - REDIS_HOST=redis
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      # <-- Исправил отступ, теперь он на уровне depends_on
      - weather_network

networks:
  weather_network:
    name: weather_network
